from __future__ import annotations

import math
import numpy as np
import os
import torch
import warp as wp
from collections.abc import Sequence
from copy import deepcopy
from dataclasses import MISSING
from typing import TYPE_CHECKING

from isaaclab.assets import Articulation
from isaaclab.managers import CommandTerm, CommandTermCfg
from isaaclab.markers import VisualizationMarkers, VisualizationMarkersCfg
from isaaclab.markers.config import FRAME_MARKER_CFG
from isaaclab.utils import configclass
from isaaclab.utils.math import (
    quat_apply,
    quat_error_magnitude,
    quat_from_euler_xyz,
    quat_inv,
    quat_mul,
    sample_uniform,
    yaw_quat,
)

if TYPE_CHECKING:
    from isaaclab.envs import ManagerBasedRLEnv


def _npz_name_list(data: np.lib.npyio.NpzFile, key: str) -> list[str] | None:
    if key not in data:
        return None
    values = np.asarray(data[key])
    if values.ndim == 0:
        return [str(values.item())]
    return [str(v) for v in values.tolist()]


def _pad_legacy_magicbot_z1_head_joint(
    joint_pos: torch.Tensor,
    joint_vel: torch.Tensor,
    expected_joint_names: Sequence[str],
) -> tuple[torch.Tensor, torch.Tensor] | None:
    if (
        len(expected_joint_names) == joint_pos.shape[1] + 1
        and expected_joint_names[-1] == "head_joint"
        and joint_pos.shape[1] == 23
        and joint_vel.shape[1] == joint_pos.shape[1]
    ):
        head_pos = torch.zeros((joint_pos.shape[0], 1), dtype=joint_pos.dtype, device=joint_pos.device)
        head_vel = torch.zeros_like(head_pos)
        return torch.cat((joint_pos, head_pos), dim=1), torch.cat((joint_vel, head_vel), dim=1)
    return None


class MotionLoader:
    def __init__(
        self,
        motion_file: str,
        body_indexes: Sequence[int] | None,
        device: str = "cpu",
        expected_joint_names: Sequence[str] | None = None,
        target_body_names: Sequence[str] | None = None,
    ):
        assert os.path.isfile(motion_file), f"Invalid file path: {motion_file}"
        with np.load(motion_file, allow_pickle=True) as data:
            fps = data["fps"]
            if isinstance(fps, np.ndarray):
                fps = fps.item() if fps.size == 1 else float(fps.flatten()[0])
            self.fps = float(fps)

            motion_joint_names = _npz_name_list(data, "joint_names")
            motion_body_names = _npz_name_list(data, "body_names")

            required_keys = (
                "joint_pos",
                "joint_vel",
                "body_pos_w",
                "body_quat_w",
                "body_lin_vel_w",
                "body_ang_vel_w",
            )
            missing_keys = [key for key in required_keys if key not in data]
            if missing_keys:
                available_keys = ", ".join(data.files)
                raise ValueError(
                    f"Motion file {motion_file} is missing required tracking arrays: {missing_keys}. "
                    "Use a full robot-motion NPZ generated by scripts/csv_to_npz_local.py. "
                    f"Available arrays: [{available_keys}]"
                )

            joint_pos = torch.tensor(data["joint_pos"], dtype=torch.float32, device=device)
            joint_vel = torch.tensor(data["joint_vel"], dtype=torch.float32, device=device)
            self.joint_pos, self.joint_vel = self._resolve_joint_data(
                joint_pos,
                joint_vel,
                expected_joint_names=expected_joint_names,
                motion_joint_names=motion_joint_names,
                motion_file=motion_file,
            )

            body_tensors = [
                torch.tensor(data["body_pos_w"], dtype=torch.float32, device=device),
                torch.tensor(data["body_quat_w"], dtype=torch.float32, device=device),
                torch.tensor(data["body_lin_vel_w"], dtype=torch.float32, device=device),
                torch.tensor(data["body_ang_vel_w"], dtype=torch.float32, device=device),
            ]
            (
                self._body_pos_w,
                self._body_quat_w,
                self._body_lin_vel_w,
                self._body_ang_vel_w,
                self._body_indexes,
            ) = self._resolve_body_data(
                body_tensors,
                body_indexes=body_indexes,
                target_body_names=target_body_names,
                motion_body_names=motion_body_names,
                motion_file=motion_file,
            )
        self.time_step_total = self.joint_pos.shape[0]

    @staticmethod
    def _resolve_joint_data(
        joint_pos: torch.Tensor,
        joint_vel: torch.Tensor,
        expected_joint_names: Sequence[str] | None,
        motion_joint_names: Sequence[str] | None,
        motion_file: str,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        if expected_joint_names is None:
            return joint_pos, joint_vel

        expected_joint_names = list(expected_joint_names)

        if motion_joint_names is not None:
            if joint_pos.shape[1] != len(motion_joint_names):
                raise ValueError(
                    f"joint_names metadata length mismatch in {motion_file}: "
                    f"{len(motion_joint_names)} names vs joint_pos dim {joint_pos.shape[1]}"
                )
            motion_index_by_name = {name: idx for idx, name in enumerate(motion_joint_names)}
            missing = [name for name in expected_joint_names if name not in motion_index_by_name]
            if missing:
                raise ValueError(
                    f"Motion joint_names in {motion_file} are missing required joints: {missing}. "
                    "Regenerate the motion with the updated robot model."
                )
            remapped_joint_pos = torch.zeros((joint_pos.shape[0], len(expected_joint_names)), dtype=joint_pos.dtype, device=joint_pos.device)
            remapped_joint_vel = torch.zeros_like(remapped_joint_pos)
            for dst_idx, name in enumerate(expected_joint_names):
                src_idx = motion_index_by_name[name]
                remapped_joint_pos[:, dst_idx] = joint_pos[:, src_idx]
                remapped_joint_vel[:, dst_idx] = joint_vel[:, src_idx]
            return remapped_joint_pos, remapped_joint_vel

        if joint_pos.shape[1] == len(expected_joint_names):
            return joint_pos, joint_vel

        padded_legacy_magicbot = _pad_legacy_magicbot_z1_head_joint(joint_pos, joint_vel, expected_joint_names)
        if padded_legacy_magicbot is not None:
            return padded_legacy_magicbot

        raise ValueError(
            f"Motion joint_pos dim mismatch for {motion_file}: expected {len(expected_joint_names)}, "
            f"got {joint_pos.shape[1]}. Regenerate the motion with the updated robot model."
        )

    @staticmethod
    def _resolve_body_data(
        body_tensors: list[torch.Tensor],
        body_indexes: Sequence[int] | None,
        target_body_names: Sequence[str] | None,
        motion_body_names: Sequence[str] | None,
        motion_file: str,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor | None]:
        body_pos_w, body_quat_w, body_lin_vel_w, body_ang_vel_w = body_tensors
        raw_body_count = body_pos_w.shape[1]

        if motion_body_names is not None:
            if raw_body_count != len(motion_body_names):
                raise ValueError(
                    f"body_names metadata length mismatch in {motion_file}: "
                    f"{len(motion_body_names)} names vs body_pos_w dim {raw_body_count}"
                )
            if target_body_names is not None:
                motion_index_by_name = {name: idx for idx, name in enumerate(motion_body_names)}
                missing = [name for name in target_body_names if name not in motion_index_by_name]
                if missing:
                    raise ValueError(
                        f"Motion body_names in {motion_file} are missing required bodies: {missing}. "
                        "Regenerate the motion with the updated robot model."
                    )
                select_ids = [motion_index_by_name[name] for name in target_body_names]
                return (
                    body_pos_w[:, select_ids],
                    body_quat_w[:, select_ids],
                    body_lin_vel_w[:, select_ids],
                    body_ang_vel_w[:, select_ids],
                    None,
                )
            return body_pos_w, body_quat_w, body_lin_vel_w, body_ang_vel_w, None

        if target_body_names is not None and raw_body_count == len(target_body_names):
            return body_pos_w, body_quat_w, body_lin_vel_w, body_ang_vel_w, None

        if body_indexes is None:
            return body_pos_w, body_quat_w, body_lin_vel_w, body_ang_vel_w, None

        body_indexes = torch.as_tensor(body_indexes, dtype=torch.long, device=body_pos_w.device)
        if body_indexes.numel() and int(body_indexes.max().item()) >= raw_body_count:
            raise ValueError(
                f"Motion body_pos_w dim mismatch for {motion_file}: requested body index "
                f"{int(body_indexes.max().item())}, but body_pos_w only has {raw_body_count} bodies. "
                "Regenerate the motion with scripts/csv_to_npz_local.py so body_names metadata is saved."
            )
        return body_pos_w, body_quat_w, body_lin_vel_w, body_ang_vel_w, body_indexes

    @property
    def body_pos_w(self) -> torch.Tensor:
        if self._body_indexes is None:
            return self._body_pos_w
        return self._body_pos_w[:, self._body_indexes]

    @property
    def body_quat_w(self) -> torch.Tensor:
        if self._body_indexes is None:
            return self._body_quat_w
        return self._body_quat_w[:, self._body_indexes]

    @property
    def body_lin_vel_w(self) -> torch.Tensor:
        if self._body_indexes is None:
            return self._body_lin_vel_w
        return self._body_lin_vel_w[:, self._body_indexes]

    @property
    def body_ang_vel_w(self) -> torch.Tensor:
        if self._body_indexes is None:
            return self._body_ang_vel_w
        return self._body_ang_vel_w[:, self._body_indexes]


class MotionCommand(CommandTerm):
    cfg: MotionCommandCfg

    def __init__(self, cfg: MotionCommandCfg, env: ManagerBasedRLEnv):
        super().__init__(cfg, env)

        self.robot: Articulation = env.scene[cfg.asset_name]
        self.robot_anchor_body_index = self.robot.body_names.index(self.cfg.anchor_body_name)
        self.motion_anchor_body_index = self.cfg.body_names.index(self.cfg.anchor_body_name)
        self.body_indexes = torch.tensor(
            self.robot.find_bodies(self.cfg.body_names, preserve_order=True)[0], dtype=torch.long, device=self.device
        )
        reset_exclude_joint_names = list(getattr(self.cfg, "reset_exclude_joint_names", []) or [])
        if reset_exclude_joint_names:
            joint_index_by_name = {name: idx for idx, name in enumerate(self.robot.joint_names)}
            missing_joint_names = [name for name in reset_exclude_joint_names if name not in joint_index_by_name]
            if missing_joint_names:
                raise ValueError(
                    f"reset_exclude_joint_names contains joints not present on robot {cfg.asset_name}: "
                    f"{missing_joint_names}"
                )
            self._reset_exclude_joint_ids = torch.tensor(
                [joint_index_by_name[name] for name in reset_exclude_joint_names],
                dtype=torch.long,
                device=self.device,
            )
        else:
            self._reset_exclude_joint_ids = None

        motion_files = list(getattr(self.cfg, "motion_files", []) or [])
        if not motion_files:
            motion_files = [self.cfg.motion_file]
        for motion_file in motion_files:
            if not os.path.isfile(motion_file):
                raise FileNotFoundError(f"Invalid motion file path: {motion_file}")

        self.motions = [
            MotionLoader(
                motion_file,
                self.body_indexes,
                device=self.device,
                expected_joint_names=self.robot.joint_names,
                target_body_names=self.cfg.body_names,
            )
            for motion_file in motion_files
        ]
        self.motion = self.motions[0]
        self.motion_count = len(self.motions)
        self.time_steps = torch.zeros(self.num_envs, dtype=torch.long, device=self.device)
        self.motion_ids = self._sample_motion_ids(self.num_envs)
        self.body_pos_relative_w = torch.zeros(self.num_envs, len(cfg.body_names), 3, device=self.device)
        self.body_quat_relative_w = torch.zeros(self.num_envs, len(cfg.body_names), 4, device=self.device)
        self.body_quat_relative_w[:, :, 0] = 1.0
        self._ground_reference_z_offset = torch.zeros(self.num_envs, dtype=torch.float32, device=self.device)

        ref_joint_shape = self.motion.joint_pos.shape[1:]
        ref_body_shape = self.motion.body_pos_w.shape[1:]
        for motion in self.motions[1:]:
            if motion.joint_pos.shape[1:] != ref_joint_shape:
                raise ValueError("All motions must have the same joint_pos shape.")
            if motion.body_pos_w.shape[1:] != ref_body_shape:
                raise ValueError("All motions must have the same body_pos_w shape.")

        self._motion_lengths = torch.tensor(
            [motion.time_step_total for motion in self.motions], dtype=torch.long, device=self.device
        )
        self._motion_hold_seconds = float(getattr(self.cfg, "motion_hold_seconds", 0.0) or 0.0)
        self._motion_hold_frames = torch.tensor(
            [max(0, int(round(motion.fps * self._motion_hold_seconds))) for motion in self.motions],
            dtype=torch.long,
            device=self.device,
        )
        self._hold_steps = torch.zeros(self.num_envs, dtype=torch.long, device=self.device)
        self._pause_prob = float(getattr(self.cfg, "random_pause_prob", 0.0) or 0.0)
        pause_range = getattr(self.cfg, "random_pause_duration_s", (0.0, 0.0)) or (0.0, 0.0)
        pause_min_s, pause_max_s = float(pause_range[0]), float(pause_range[1])
        if pause_max_s < pause_min_s:
            pause_min_s, pause_max_s = pause_max_s, pause_min_s
        self._pause_min_frames = torch.tensor(
            [max(0, int(round(motion.fps * pause_min_s))) for motion in self.motions],
            dtype=torch.long,
            device=self.device,
        )
        self._pause_max_frames = torch.tensor(
            [max(0, int(round(motion.fps * pause_max_s))) for motion in self.motions],
            dtype=torch.long,
            device=self.device,
        )
        self._pause_steps_left = torch.zeros(self.num_envs, dtype=torch.long, device=self.device)
        self._motion_bin_counts = [
            int(motion.time_step_total // (1 / (env.cfg.decimation * env.cfg.sim.dt))) + 1 for motion in self.motions
        ]
        self._motion_bin_failed_count = [
            torch.zeros(bin_count, dtype=torch.float, device=self.device) for bin_count in self._motion_bin_counts
        ]
        self._motion_current_bin_failed = [
            torch.zeros(bin_count, dtype=torch.float, device=self.device) for bin_count in self._motion_bin_counts
        ]
        self.kernel = torch.tensor(
            [self.cfg.adaptive_lambda**i for i in range(self.cfg.adaptive_kernel_size)], device=self.device
        )
        self.kernel = self.kernel / self.kernel.sum()

        self.metrics["error_anchor_pos"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["error_anchor_rot"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["error_anchor_lin_vel"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["error_anchor_ang_vel"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["error_body_pos"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["error_body_rot"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["error_joint_pos"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["error_joint_vel"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["sampling_entropy"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["sampling_top1_prob"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["sampling_top1_bin"] = torch.zeros(self.num_envs, device=self.device)

    def _sample_motion_ids(self, count: int) -> torch.Tensor:
        if self.motion_count == 1:
            return torch.zeros(count, dtype=torch.long, device=self.device)
        weights = getattr(self.cfg, "motion_sampling_weights", None)
        if weights:
            if len(weights) != self.motion_count:
                raise ValueError("motion_sampling_weights length must match motion_files length.")
            weight_tensor = torch.tensor(weights, dtype=torch.float, device=self.device)
            weight_tensor = weight_tensor / weight_tensor.sum()
            return torch.multinomial(weight_tensor, count, replacement=True)
        return torch.randint(0, self.motion_count, (count,), device=self.device)

    def _gather_motion_attr(self, attr: str) -> torch.Tensor:
        if self.motion_count == 1:
            data = getattr(self.motion, attr)
            return data[self.time_steps]
        out = None
        for motion_id, motion in enumerate(self.motions):
            env_mask = self.motion_ids == motion_id
            if not torch.any(env_mask):
                continue
            env_ids = torch.where(env_mask)[0]
            data = getattr(motion, attr)
            gathered = data[self.time_steps[env_ids]]
            if out is None:
                out = torch.zeros(
                    (self.num_envs,) + gathered.shape[1:], dtype=gathered.dtype, device=self.device
                )
            out[env_ids] = gathered
        if out is None:
            data = getattr(self.motion, attr)
            out = torch.zeros((self.num_envs,) + data.shape[1:], dtype=data.dtype, device=self.device)
        return out

    @property
    def command(self) -> torch.Tensor:  # TODO Consider again if this is the best observation
        return torch.cat([self.joint_pos, self.joint_vel], dim=1)

    @property
    def joint_pos(self) -> torch.Tensor:
        return self._gather_motion_attr("joint_pos")

    @property
    def joint_vel(self) -> torch.Tensor:
        return self._gather_motion_attr("joint_vel")

    @property
    def body_pos_w(self) -> torch.Tensor:
        body_pos_w = self._gather_motion_attr("body_pos_w") + self._env.scene.env_origins[:, None, :]
        if bool(getattr(self.cfg, "ground_reference_on_reset", False)):
            body_pos_w = body_pos_w.clone()
            body_pos_w[:, :, 2] -= self._ground_reference_z_offset[:, None]
        return body_pos_w

    @property
    def body_quat_w(self) -> torch.Tensor:
        return self._gather_motion_attr("body_quat_w")

    @property
    def body_lin_vel_w(self) -> torch.Tensor:
        return self._gather_motion_attr("body_lin_vel_w")

    @property
    def body_ang_vel_w(self) -> torch.Tensor:
        return self._gather_motion_attr("body_ang_vel_w")

    @property
    def anchor_pos_w(self) -> torch.Tensor:
        return self.body_pos_w[:, self.motion_anchor_body_index]

    @property
    def anchor_quat_w(self) -> torch.Tensor:
        return self.body_quat_w[:, self.motion_anchor_body_index]

    @property
    def anchor_lin_vel_w(self) -> torch.Tensor:
        return self.body_lin_vel_w[:, self.motion_anchor_body_index]

    @property
    def anchor_ang_vel_w(self) -> torch.Tensor:
        return self.body_ang_vel_w[:, self.motion_anchor_body_index]

    @property
    def robot_joint_pos(self) -> torch.Tensor:
        return self._robot_data_to_torch(self.robot.data.joint_pos)

    @property
    def robot_joint_vel(self) -> torch.Tensor:
        return self._robot_data_to_torch(self.robot.data.joint_vel)

    def _robot_data_to_torch(self, value) -> torch.Tensor:
        if torch.is_tensor(value):
            return value
        return wp.to_torch(value).to(device=self.device)

    @property
    def robot_body_pos_w(self) -> torch.Tensor:
        return self._robot_data_to_torch(self.robot.data.body_pos_w)[:, self.body_indexes]

    @property
    def robot_body_quat_w(self) -> torch.Tensor:
        return self._robot_data_to_torch(self.robot.data.body_quat_w)[:, self.body_indexes]

    @property
    def robot_body_lin_vel_w(self) -> torch.Tensor:
        return self._robot_data_to_torch(self.robot.data.body_lin_vel_w)[:, self.body_indexes]

    @property
    def robot_body_ang_vel_w(self) -> torch.Tensor:
        return self._robot_data_to_torch(self.robot.data.body_ang_vel_w)[:, self.body_indexes]

    @property
    def robot_anchor_pos_w(self) -> torch.Tensor:
        return self._robot_data_to_torch(self.robot.data.body_pos_w)[:, self.robot_anchor_body_index]

    @property
    def robot_anchor_quat_w(self) -> torch.Tensor:
        return self._robot_data_to_torch(self.robot.data.body_quat_w)[:, self.robot_anchor_body_index]

    @property
    def robot_anchor_lin_vel_w(self) -> torch.Tensor:
        return self._robot_data_to_torch(self.robot.data.body_lin_vel_w)[:, self.robot_anchor_body_index]

    @property
    def robot_anchor_ang_vel_w(self) -> torch.Tensor:
        return self._robot_data_to_torch(self.robot.data.body_ang_vel_w)[:, self.robot_anchor_body_index]

    def _update_metrics(self):
        self.metrics["error_anchor_pos"] = torch.norm(self.anchor_pos_w - self.robot_anchor_pos_w, dim=-1)
        self.metrics["error_anchor_rot"] = quat_error_magnitude(self.anchor_quat_w, self.robot_anchor_quat_w)
        self.metrics["error_anchor_lin_vel"] = torch.norm(self.anchor_lin_vel_w - self.robot_anchor_lin_vel_w, dim=-1)
        self.metrics["error_anchor_ang_vel"] = torch.norm(self.anchor_ang_vel_w - self.robot_anchor_ang_vel_w, dim=-1)

        self.metrics["error_body_pos"] = torch.norm(self.body_pos_relative_w - self.robot_body_pos_w, dim=-1).mean(
            dim=-1
        )
        self.metrics["error_body_rot"] = quat_error_magnitude(self.body_quat_relative_w, self.robot_body_quat_w).mean(
            dim=-1
        )

        self.metrics["error_body_lin_vel"] = torch.norm(self.body_lin_vel_w - self.robot_body_lin_vel_w, dim=-1).mean(
            dim=-1
        )
        self.metrics["error_body_ang_vel"] = torch.norm(self.body_ang_vel_w - self.robot_body_ang_vel_w, dim=-1).mean(
            dim=-1
        )

        self.metrics["error_joint_pos"] = torch.norm(self.joint_pos - self.robot_joint_pos, dim=-1)
        self.metrics["error_joint_vel"] = torch.norm(self.joint_vel - self.robot_joint_vel, dim=-1)

    def _adaptive_sampling(self, env_ids: Sequence[int]):
        if len(env_ids) == 0:
            return

        episode_failed = self._env.termination_manager.terminated[env_ids]

        for motion_id in range(self.motion_count):
            env_mask = self.motion_ids[env_ids] == motion_id
            if not torch.any(env_mask):
                continue
            motion_env_ids = env_ids[env_mask]
            motion_len = int(self._motion_lengths[motion_id].item())
            bin_count = self._motion_bin_counts[motion_id]
            motion_start_step = getattr(self.cfg, "motion_start_step", None)
            if motion_start_step is not None:
                start_step = max(0, min(int(motion_start_step), max(motion_len - 1, 0)))
                self.time_steps[motion_env_ids] = start_step
                continue

            if torch.any(episode_failed[env_mask]):
                current_bin_index = torch.clamp(
                    (self.time_steps[motion_env_ids] * bin_count) // max(motion_len, 1), 0, bin_count - 1
                )
                fail_bins = current_bin_index[episode_failed[env_mask]]
                self._motion_current_bin_failed[motion_id][:] = torch.bincount(fail_bins, minlength=bin_count)

            sampling_probabilities = (
                self._motion_bin_failed_count[motion_id] + self.cfg.adaptive_uniform_ratio / float(bin_count)
            )
            sampling_probabilities = torch.nn.functional.pad(
                sampling_probabilities.unsqueeze(0).unsqueeze(0),
                (0, self.cfg.adaptive_kernel_size - 1),  # Non-causal kernel
                mode="replicate",
            )
            sampling_probabilities = torch.nn.functional.conv1d(
                sampling_probabilities, self.kernel.view(1, 1, -1)
            ).view(-1)
            sampling_probabilities = sampling_probabilities / sampling_probabilities.sum()

            sampled_bins = torch.multinomial(sampling_probabilities, len(motion_env_ids), replacement=True)
            self.time_steps[motion_env_ids] = (
                (sampled_bins + sample_uniform(0.0, 1.0, (len(motion_env_ids),), device=self.device))
                / bin_count
                * (max(motion_len - 1, 0))
            ).long()

            # Metrics
            H = -(sampling_probabilities * (sampling_probabilities + 1e-12).log()).sum()
            H_norm = H / math.log(bin_count)
            pmax, imax = sampling_probabilities.max(dim=0)
            self.metrics["sampling_entropy"][motion_env_ids] = H_norm
            self.metrics["sampling_top1_prob"][motion_env_ids] = pmax
            self.metrics["sampling_top1_bin"][motion_env_ids] = imax.float() / bin_count

    def _resample_command(self, env_ids: Sequence[int]):
        if len(env_ids) == 0:
            return
        # Clear any pending pause when resampling a new motion segment.
        self._pause_steps_left[env_ids] = 0
        if self.motion_count > 1:
            self.motion_ids[env_ids] = self._sample_motion_ids(len(env_ids))
        self._adaptive_sampling(env_ids)

        motion_body_pos_w = self._gather_motion_attr("body_pos_w") + self._env.scene.env_origins[:, None, :]
        root_pos = motion_body_pos_w[:, 0].clone()
        root_ori = self.body_quat_w[:, 0].clone()
        root_lin_vel = self.body_lin_vel_w[:, 0].clone()
        root_ang_vel = self.body_ang_vel_w[:, 0].clone()

        if bool(getattr(self.cfg, "ground_reference_on_reset", False)):
            clearance = float(getattr(self.cfg, "ground_reference_clearance", 0.0) or 0.0)
            body_z = motion_body_pos_w[env_ids, :, 2]
            min_body_z = body_z.min(dim=1).values
            self._ground_reference_z_offset[env_ids] = min_body_z - clearance
            root_pos[env_ids, 2] -= self._ground_reference_z_offset[env_ids]
        else:
            self._ground_reference_z_offset[env_ids] = 0.0

        range_list = [self.cfg.pose_range.get(key, (0.0, 0.0)) for key in ["x", "y", "z", "roll", "pitch", "yaw"]]
        ranges = torch.tensor(range_list, device=self.device)
        rand_samples = sample_uniform(ranges[:, 0], ranges[:, 1], (len(env_ids), 6), device=self.device)
        root_pos[env_ids] += rand_samples[:, 0:3]
        orientations_delta = quat_from_euler_xyz(rand_samples[:, 3], rand_samples[:, 4], rand_samples[:, 5])
        root_ori[env_ids] = quat_mul(orientations_delta, root_ori[env_ids])
        range_list = [self.cfg.velocity_range.get(key, (0.0, 0.0)) for key in ["x", "y", "z", "roll", "pitch", "yaw"]]
        ranges = torch.tensor(range_list, device=self.device)
        rand_samples = sample_uniform(ranges[:, 0], ranges[:, 1], (len(env_ids), 6), device=self.device)
        root_lin_vel[env_ids] += rand_samples[:, :3]
        root_ang_vel[env_ids] += rand_samples[:, 3:]

        joint_pos = self.joint_pos[env_ids].clone()
        joint_vel = self.joint_vel[env_ids].clone()

        joint_pos += sample_uniform(*self.cfg.joint_position_range, joint_pos.shape, joint_pos.device)
        if self._reset_exclude_joint_ids is not None and self._reset_exclude_joint_ids.numel() > 0:
            default_joint_pos = self._robot_data_to_torch(self.robot.data.default_joint_pos)[env_ids]
            joint_pos[:, self._reset_exclude_joint_ids] = default_joint_pos[:, self._reset_exclude_joint_ids]
            joint_vel[:, self._reset_exclude_joint_ids] = 0.0
        soft_joint_pos_limits = self._robot_data_to_torch(self.robot.data.soft_joint_pos_limits)[env_ids]
        joint_pos = torch.clip(joint_pos, soft_joint_pos_limits[:, :, 0], soft_joint_pos_limits[:, :, 1])
        self.robot.write_joint_state_to_sim(joint_pos, joint_vel, env_ids=env_ids)
        self.robot.write_root_state_to_sim(
            torch.cat([root_pos[env_ids], root_ori[env_ids], root_lin_vel[env_ids], root_ang_vel[env_ids]], dim=-1),
            env_ids=env_ids,
        )

    def _update_command(self):
        pause_mask = self._pause_steps_left > 0
        if self._pause_prob > 0.0 and torch.any(~pause_mask):
            max_pause_frames = int(torch.max(self._pause_max_frames).item()) if len(self._pause_max_frames) else 0
            if max_pause_frames > 0:
                new_pause = (~pause_mask) & (torch.rand(self.num_envs, device=self.device) < self._pause_prob)
                if torch.any(new_pause):
                    env_ids = torch.where(new_pause)[0]
                    motion_ids = self.motion_ids[env_ids]
                    min_frames = self._pause_min_frames[motion_ids]
                    max_frames = self._pause_max_frames[motion_ids]
                    max_frames = torch.maximum(max_frames, min_frames)
                    span = (max_frames - min_frames).float()
                    if torch.all(span == 0):
                        lengths = min_frames
                    else:
                        lengths = min_frames + torch.floor(torch.rand(len(env_ids), device=self.device) * (span + 1)).long()
                    valid = lengths > 0
                    if torch.any(valid):
                        self._pause_steps_left[env_ids[valid]] = lengths[valid]
                        pause_mask = self._pause_steps_left > 0

        advance_mask = ~pause_mask
        if torch.any(advance_mask):
            self.time_steps[advance_mask] += 1

        motion_lengths = self._motion_lengths[self.motion_ids]
        at_end = self.time_steps >= motion_lengths
        if torch.any(at_end):
            # Keep indices pinned to the last frame while holding.
            self.time_steps = torch.where(at_end, motion_lengths - 1, self.time_steps)
            hold_frames = self._motion_hold_frames[self.motion_ids]
            self._hold_steps[at_end] += 1
            ready = at_end & ((hold_frames <= 0) | (self._hold_steps >= hold_frames))
            if torch.any(ready):
                env_ids = torch.where(ready)[0]
                self._hold_steps[env_ids] = 0
                self._resample_command(env_ids)
        # reset hold counters for envs not at end
        if torch.any(~at_end):
            self._hold_steps[~at_end] = 0

        if torch.any(pause_mask):
            self._pause_steps_left[pause_mask] -= 1
            self._pause_steps_left = torch.clamp(self._pause_steps_left, min=0)

        anchor_pos_w_repeat = self.anchor_pos_w[:, None, :].repeat(1, len(self.cfg.body_names), 1)
        anchor_quat_w_repeat = self.anchor_quat_w[:, None, :].repeat(1, len(self.cfg.body_names), 1)
        robot_anchor_pos_w_repeat = self.robot_anchor_pos_w[:, None, :].repeat(1, len(self.cfg.body_names), 1)
        robot_anchor_quat_w_repeat = self.robot_anchor_quat_w[:, None, :].repeat(1, len(self.cfg.body_names), 1)

        delta_pos_w = robot_anchor_pos_w_repeat
        delta_pos_w[..., 2] = anchor_pos_w_repeat[..., 2]
        delta_ori_w = yaw_quat(quat_mul(robot_anchor_quat_w_repeat, quat_inv(anchor_quat_w_repeat)))

        self.body_quat_relative_w = quat_mul(delta_ori_w, self.body_quat_w)
        self.body_pos_relative_w = delta_pos_w + quat_apply(delta_ori_w, self.body_pos_w - anchor_pos_w_repeat)

        for motion_id in range(self.motion_count):
            self._motion_bin_failed_count[motion_id] = (
                self.cfg.adaptive_alpha * self._motion_current_bin_failed[motion_id]
                + (1 - self.cfg.adaptive_alpha) * self._motion_bin_failed_count[motion_id]
            )
            self._motion_current_bin_failed[motion_id].zero_()

    def set_random_pause(self, pause_prob: float, duration_s: tuple[float, float]) -> None:
        """Update random-pause settings at runtime for stop curriculum."""
        self._pause_prob = max(0.0, float(pause_prob))
        pause_min_s = max(0.0, float(duration_s[0]))
        pause_max_s = max(0.0, float(duration_s[1]))
        if pause_max_s < pause_min_s:
            pause_min_s, pause_max_s = pause_max_s, pause_min_s
        self._pause_min_frames = torch.tensor(
            [max(0, int(round(motion.fps * pause_min_s))) for motion in self.motions],
            dtype=torch.long,
            device=self.device,
        )
        self._pause_max_frames = torch.tensor(
            [max(0, int(round(motion.fps * pause_max_s))) for motion in self.motions],
            dtype=torch.long,
            device=self.device,
        )

    def _set_debug_vis_impl(self, debug_vis: bool):
        if debug_vis:
            if not hasattr(self, "current_anchor_visualizer"):
                self.current_anchor_visualizer = VisualizationMarkers(
                    self.cfg.anchor_visualizer_cfg.replace(prim_path="/Visuals/Command/current/anchor")
                )
                self.goal_anchor_visualizer = VisualizationMarkers(
                    self.cfg.anchor_visualizer_cfg.replace(prim_path="/Visuals/Command/goal/anchor")
                )

                self.current_body_visualizers = []
                self.goal_body_visualizers = []
                for name in self.cfg.body_names:
                    self.current_body_visualizers.append(
                        VisualizationMarkers(
                            self.cfg.body_visualizer_cfg.replace(prim_path="/Visuals/Command/current/" + name)
                        )
                    )
                    self.goal_body_visualizers.append(
                        VisualizationMarkers(
                            self.cfg.body_visualizer_cfg.replace(prim_path="/Visuals/Command/goal/" + name)
                        )
                    )

            self.current_anchor_visualizer.set_visibility(True)
            self.goal_anchor_visualizer.set_visibility(True)
            for i in range(len(self.cfg.body_names)):
                self.current_body_visualizers[i].set_visibility(True)
                self.goal_body_visualizers[i].set_visibility(True)

        else:
            if hasattr(self, "current_anchor_visualizer"):
                self.current_anchor_visualizer.set_visibility(False)
                self.goal_anchor_visualizer.set_visibility(False)
                for i in range(len(self.cfg.body_names)):
                    self.current_body_visualizers[i].set_visibility(False)
                    self.goal_body_visualizers[i].set_visibility(False)

    def _debug_vis_callback(self, event):
        if not self.robot.is_initialized:
            return

        self.current_anchor_visualizer.visualize(self.robot_anchor_pos_w, self.robot_anchor_quat_w)
        self.goal_anchor_visualizer.visualize(self.anchor_pos_w, self.anchor_quat_w)

        for i in range(len(self.cfg.body_names)):
            self.current_body_visualizers[i].visualize(self.robot_body_pos_w[:, i], self.robot_body_quat_w[:, i])
            self.goal_body_visualizers[i].visualize(self.body_pos_relative_w[:, i], self.body_quat_relative_w[:, i])


def _single_frame_marker_cfg(prim_path: str, scale: tuple[float, float, float]) -> VisualizationMarkersCfg:
    """Create a frame-only marker config.

    FRAME_MARKER_CFG ships with a second ``connecting_line`` prototype, but MotionCommand only ever
    visualizes prototype 0. On Isaac Sim 4.5 this leaves the unused proto1 path spewing
    ``Empty InstanceIndices`` / ``ProtoIndex ... out of bounds`` warnings under ``/Visuals/Command/*``.
    """
    return VisualizationMarkersCfg(
        prim_path=prim_path,
        markers={
            "frame": deepcopy(FRAME_MARKER_CFG.markers["frame"]).replace(scale=scale),
        },
    )


@configclass
class MotionCommandCfg(CommandTermCfg):
    """Configuration for the motion command."""

    class_type: type = MotionCommand

    asset_name: str = MISSING

    motion_file: str = MISSING
    motion_files: list[str] | None = None
    motion_sampling_weights: list[float] | None = None
    anchor_body_name: str = MISSING
    body_names: list[str] = MISSING

    pose_range: dict[str, tuple[float, float]] = {}
    velocity_range: dict[str, tuple[float, float]] = {}

    joint_position_range: tuple[float, float] = (-0.52, 0.52)
    reset_exclude_joint_names: list[str] | None = None

    adaptive_kernel_size: int = 1
    adaptive_lambda: float = 0.8
    adaptive_uniform_ratio: float = 0.1
    adaptive_alpha: float = 0.001
    # Hold the last frame for extra stability before resampling (seconds).
    motion_hold_seconds: float = 0.0
    # Random pause to freeze the current motion frame (seconds).
    random_pause_prob: float = 0.0
    random_pause_duration_s: tuple[float, float] = (0.0, 0.0)
    motion_start_step: int | None = None
    # When enabled, shift root z on reset so the lowest tracked body starts at ground level.
    ground_reference_on_reset: bool = False
    ground_reference_clearance: float = 0.0

    anchor_visualizer_cfg: VisualizationMarkersCfg = _single_frame_marker_cfg(
        prim_path="/Visuals/Command/pose",
        scale=(0.2, 0.2, 0.2),
    )

    body_visualizer_cfg: VisualizationMarkersCfg = _single_frame_marker_cfg(
        prim_path="/Visuals/Command/pose",
        scale=(0.1, 0.1, 0.1),
    )
